### ISSUE TITLE
本服务支持最大连接数是多少

### ISSUE THREAD

**Issue by shaoneng111** [monkeyWie/proxyee#146]
这个代理最大连接数能支持多少？当qps比较高的情况下，经常出现代理失败情况。（使用locust压测）

215 | GET | *** | 'ProxyError(MaxRetryError("HTTPSConnectionPool(host=\'***\', port=443): Max retries exceeded with url: /api/v3/forbidRuleList?ruleType=appkey (Caused by ProxyError(\'Cannot connect to proxy.\', ConnectionResetError(54, \'Connection reset by peer\')))"))'

749 | GET | *** | 'ProxyError(MaxRetryError("HTTPSConnectionPool(host=\'***', port=443): Max retries exceeded with url: /api/v3/forbidRuleList?ruleType=appkey (Caused by ProxyError(\'Cannot connect to proxy.\', RemoteDisconnected(\'Remote end closed connection without response\')))"))

**Comment by shaoneng111** [comment]
服务端报错是这个：
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:378)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1108)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:345)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:647)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:582)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:461)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

**Comment by monkeyWie** [comment]
你压测qps有多少，理论上qps过10k没问题
