### ISSUE TITLE
https 证书报错 javax.net.ssl.SSLException: Received fatal alert: certificate_unknown

### ISSUE THREAD

**Issue by daoshengkeji** [monkeyWie/proxyee#192]
[2022-01-12 00:16:51,608 nioEventLoopGroup-4-3] WARN  io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:294) An exception 'java.lang.Exception: io.netty.handler.codec.DecoderException: javax.net.ssl.SSLException: Received fatal alert: certificate_unknown' [enable DEBUG level for full stacktrace] was thrown by a user handler's exceptionCaught() method while handling the following exception:
io.netty.handler.codec.DecoderException: javax.net.ssl.SSLException: Received fatal alert: certificate_unknown
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:459)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:392)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:359)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:342)
	at io.netty.handler.ssl.SslHandler.channelInactive(SslHandler.java:1028)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1429)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:947)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:822)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:465)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.net.ssl.SSLException: Received fatal alert: certificate_unknown
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1647)
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1615)
	at sun.security.ssl.SSLEngineImpl.recvAlert(SSLEngineImpl.java:1781)
	at sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:1070)
	at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:896)
	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:766)
	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624)
	at io.netty.handler.ssl.SslHandler$SslEngineType$3.unwrap(SslHandler.java:294)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1275)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1177)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1221)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
	... 18 more

**Comment by king1982** [comment]
我的偶尔有出现，我看了作者的处理方法加了host + port。具体提交可以从：https://github.com/monkeyWie/proxyee/commit/d9b0dcd33cde0c8dd98699089478c907d888f223
这个提交上看到作者修复时候提交的代码。
另外我的另外一个项目也出现这个问题了，而且是百分之一百通过不了。试了好几种方法，其中有从此项目移植证书生成策略，加host以及port。都不行。害。
另外通过查阅资料，我的这边可能还会与证书不信任有关
具体：https://community.smartbear.com/t5/SoapUI-Open-Source-Questions/javax-net-ssl-SSLHandshakeException-Received-fatal-alert-unknown/td-p/224326

**Comment by king1982** [comment]
> 有没有复现的代码，贴一下看看



> 有没有复现的代码，贴一下看看

我的是对着您的项目结合另外一个项目去改进的。嘿嘿。因为那个项目做到了socks4/socks5+http/htpps共用同一个端口，您可以参考一下。嘿嘿
https://github.com/hsiafan/cute-proxy

**Comment by monkeyWie** [comment]
@king1982 我想看看有没有100%复现成功的步骤，这样才好排查

**Comment by king1982** [comment]
> @king1982 我想看看有没有100%复现成功的步骤，这样才好排查

不好意思，我的是证书的的原因，并不是sni拓展的。打扰了啦。非常感谢大大的回复。我已经自行解决了。
