### ISSUE TITLE
连接被重置

### ISSUE THREAD

**Issue by SealinRepo** [monkeyWie/proxyee#20]
异常信息
`111111111111111
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1106)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:373)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:748)`
浏览器是Chrome

**Comment by monkeyWie** [comment]
请求地址有吗

**Comment by uroot** [comment]
我是在ie选项里边设置的http代理,然后访问任何网站都是已重置...

**Comment by monkeyWie** [comment]
你是运行的代码是？

**Comment by SealinRepo** [comment]
java -jar proxyee.jar

**Comment by monkeyWie** [comment]
jar包你自己编译的？maven下的jar包是没有main方法的啊

**Comment by SealinRepo** [comment]
是啊,我拉了一份源码,打包后运行的,去服务器看了端口已经监听了,在客户端链接重置的时候去服务端看到抛出的异常就是上边那样了..

**Comment by monkeyWie** [comment]
直接运行HttpProxyServer.java试试

**Comment by SealinRepo** [comment]
嗯,我再看下是咋回事...
