### ISSUE TITLE
Android Studio 开发时出现 Attempt to inmoke virtual method 'void lee.study.proxyee.intercept.HttpProxyInterceptPipeline.beforeRequest(io.netty.channel.Channel, io.netty.handler.codec.http.HttpContent)' on a null object reference'

### ISSUE THREAD

**Issue by hacking001** [monkeyWie/proxyee#23]
错误信息如下
`
W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'void lee.study.proxyee.intercept.HttpProxyInterceptPipeline.beforeRequest(io.netty.channel.Channel, io.netty.handler.codec.http.HttpContent)' on a null object reference
                  at lee.study.proxyee.handler.HttpProxyServerHandle.channelRead(HttpProxyServerHandle.java:103)
W/System.err:     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
                  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
                  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
                  at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
                  at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
                  at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
                  at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
                  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
                  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
W/System.err:     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
                  at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
                  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
                  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
                  at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
                  at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
                  at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
                  at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
                  at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
W/System.err:     at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
                  at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
                  at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
                  at java.lang.Thread.run(Thread.java:776)
W/System.err: java.lang.UnsupportedOperationException
W/System.err:     at java.util.regex.Matcher.group(Matcher.java:383)
                  at lee.study.proxyee.util.ProtoUtil.getRequestProto(ProtoUtil.java:32)
                  at lee.study.proxyee.handler.HttpProxyServerHandle.channelRead(HttpProxyServerHandle.java:81)
                  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
                  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
                  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
                  at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
                  at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
                  at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
W/System.err:     at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
                  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
                  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
                  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
                  at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
                  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
                  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
                  at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
                  at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
W/System.err:     at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
                  at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
                  at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
                  at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
                  at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
                  at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
                  at java.lang.Thread.run(Thread.java:776)
`
代码如下，点击 Button 的时候启动代理服务，不知道啥原因，点击之后会卡，不过开个线程去启动就行。
`
ProxyServerUtils.proxyServer = new HttpProxyServer();
        ProxyServerUtils.proxyServer = ProxyServerUtils.proxyServer.proxyInterceptInitializer(new HttpProxyInterceptInitializer()
        {
            @Override
            public void init(HttpProxyInterceptPipeline pipeline)
            {
                pipeline.addLast(new CertDownIntercept());
                pipeline.addLast(new HttpProxyIntercept()
                {

                });
            }
        });
        ProxyServerUtils.proxyServer = ProxyServerUtils.proxyServer.httpProxyExceptionHandle(new HttpProxyExceptionHandle()
        {
            @Override
            public void beforeCatch(Channel clientChannel, Throwable e) throws Exception
            {
                e.printStackTrace();
            }

            @Override
            public void afterCatch(Channel clientChannel, Channel proxyChannel, Throwable e) throws Exception
            {
                e.printStackTrace();
            }
        });
`
另外说明，我是小白

**Comment by monkeyWie** [comment]
安卓的jdk正则表达式不兼容这个代码，在ProtoUtil.getRequestProto这个方法里

**Comment by hacking001** [comment]
意思是降低 JDK 版本咯？我去试试

**Comment by hacking001** [comment]
具体需要怎么修改呢？我的设备是 Android 7.0 的，根据提示来的话，那不是最低得 Android 8.0 才能运行

**Comment by hacking001** [comment]
好了，我自己修复了，使用 java.net.URL 去获取 host port 即可

**Comment by hacking001** [comment]
CertUtil 中有几行需要最低 Android 8.0 Sdk API 26 的支持，好在暂时不需要 HTTPS

**Comment by monkeyWie** [comment]
主要是不支持那个:名称匹配符，用索引匹配就好了。 安卓的话没有测试过额，不过之前有个人在安卓上测试https会有问题，主要是底层ssl类库的问题

**Comment by hacking001** [comment]
这个函数我改了一下，现在可以正常运行了，使用的是 java.net.URL 这个类，能直接解析 host port 这些。
```
public static RequestProto getRequestProto(HttpRequest httpRequest) throws MalformedURLException
    {
        RequestProto requestProto = new RequestProto();
        // 获取 URI
        String requestUri = httpRequest.uri();
        // 检测是否带 http:// https://，java.net.URL 解析时需要，不带就默认加上 http://
        if (!requestUri.substring(0, 7).equals("http://") && !requestUri.substring(0, 8).equals("https://")) {
            requestUri = "http://" + requestUri;
        }
        // 进行解析
        URL requestUrl = new URL(requestUri);
        // 看端口是不是 443，如果是就把 http:// 改 https://
        if (requestUrl.getPort() == 443) {
            requestUri = requestUri.replaceFirst("http://", "https://");
        }
        // 再次解析
        requestUrl = new URL(requestUri);
        // 控制台输出一下 URI
        Log.e("URL", requestUri);
        String hostStr = httpRequest.headers().get(HttpHeaderNames.HOST);
        int port = requestUrl.getPort();
        if (hostStr == null) {
            hostStr = requestUrl.getHost();
        }
        String uriStr = httpRequest.uri();
        boolean isSsl = uriStr.indexOf("https") == 0 || hostStr.indexOf("https") == 0;
        if (port == -1) {
            if (isSsl) {
                port = 443;
            } else {
                port = 80;
            }
        }
        requestProto.setHost(hostStr);
        requestProto.setPort(port);
        requestProto.setSsl(isSsl);
        return requestProto;
    }
```

**Comment by hacking001** [comment]
可能对 HTTP Keep-Alive 的支持也有问题。
