### ISSUE TITLE
Error:Connection reset by peer

### ISSUE THREAD

**Issue by Metatronxl** [monkeyWie/proxyee#33]
运行test里面的`NormalHttpProxyServer`会直接提示连接被重置，采用的方法是本地执行，然后`Chrome`使用`SwitchyOmega`来代理转发

```
十一月 12, 2018 8:47:31 上午 io.netty.channel.AbstractChannelHandlerContext invokeExceptionCaught
警告: An exception 'java.lang.Exception: java.io.IOException: Connection reset by peer' [enable DEBUG level for full stacktrace] was thrown by a user handler's exceptionCaught() method while handling the following exception:
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:379)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1108)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:345)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:647)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:582)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:461)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by monkeyWie** [comment]
我这测试没问题呀，代理之后访问网页有问题吗？

**Comment by Metatronxl** [comment]
恩恩，就是访问页面返回的错误

**Comment by monkeyWie** [comment]
把你访问的地址发出来我试试看看

**Comment by Metatronxl** [comment]
就很随意的，Chorme访问www.baidu.com

**Comment by Metatronxl** [comment]
还说我SwitchyOmega设置的有问题呢？

我switchOmega设置的http和https走代理服务器

**Comment by monkeyWie** [comment]
把你SwitchyOmega设置截图出来看看

**Comment by Metatronxl** [comment]
![proxy截图](https://ws1.sinaimg.cn/large/006tNbRwly1fx5dnucf5tj31kw130jwi.jpg)

**Comment by monkeyWie** [comment]
就在默认那里填ip和端口就好，协议选http

**Comment by Metatronxl** [comment]
这样确实能访问网页啦，不过还是会存`Connection reset by peer`的情况，我再研究一下，非常感谢：P

**Comment by monkeyWie** [comment]
ok 那我把issue关了哦
