### ISSUE TITLE
运行入口直接报以下问题

### ISSUE THREAD

**Issue by darker50** [monkeyWie/proxyee#6]
十二月 04, 2017 9:25:46 下午 io.netty.channel.DefaultChannelPipeline onUnhandledInboundException
警告: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.handler.codec.DecoderException: javax.net.ssl.SSLException: Received fatal alert: unknown_ca
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:459)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.net.ssl.SSLException: Received fatal alert: unknown_ca
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1666)
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1634)
	at sun.security.ssl.SSLEngineImpl.recvAlert(SSLEngineImpl.java:1800)
	at sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:1083)
	at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:907)
	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:781)
	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624)
	at io.netty.handler.ssl.SslHandler$SslEngineType$3.unwrap(SslHandler.java:281)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1215)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1127)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1162)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
	... 16 more

运行httpProxyServer连上就报以上错误，查了google说是surper.channelRead的方法的问题，但你都override这个方法了，怎么还有这个问题啊。
http://m.php.cn/wenda/94484.html

**Comment by monkeyWie** [comment]
ca证书导入到浏览器了吗

**Comment by darker50** [comment]
@monkeyWie 我换成自己的crt文件，通过浏览器导入到系统了，还是有这个问题。

**Comment by monkeyWie** [comment]
@darker50 
请问你是用的什么操作系统和浏览器呢，先把项目里的src/resources/ca.crt导入到**浏览器受信任的根目录里**,然后启动浏览器连接代理服务器访问网页试试。
如果要用自己的CA证书，把resources里的ca.crt和ca_private.pem替换掉。

**Comment by darker50** [comment]
@monkeyWie  我是代理手机上的浏览器（安卓），已经把ca证书安装到手机上了，还是有部分报这个问题，是不是有些链接不信任这个证书导致的啊，还有就是看你在main方法定义的那个
`@Override
              public void afterResponse(Channel clientChannel, Channel proxyChannel,
                  HttpResponse httpResponse,`
这里定义的httpResponse只是一个返回的header吧，返回的body在别的方法咯

**Comment by monkeyWie** [comment]
@darker50 安卓手机上的还没有测试过，估计是证书要做处理，明天测试下看。
拦截器的话是你那样理解的没错。
```
/**
   * 拦截响应头和http协议版本及uri
   */
  public void afterResponse(Channel clientChannel, Channel proxyChannel,
      HttpResponse httpResponse, HttpProxyInterceptPipeline pipeline) throws Exception {

  }


  /**
   * 拦截http响应体,这里需要自己去处理HttpContent,因为响应体太大直接转成文本可能会导致内存溢出
   */
  public void afterResponse(Channel clientChannel, Channel proxyChannel,
      HttpContent httpContent, HttpProxyInterceptPipeline pipeline) throws Exception {
      
  }
```

**Comment by darker50** [comment]
确认了，报那些错误的原因就是证书的问题，当时用手机请求的时候后台还有一些请求，那些请求导致报那个证书的问题，感谢，感谢。
拦截器对gzip压缩结束直接打印的结果会有乱码，我目前的处理方法，是请求的时候不用压缩，返回的结果也就没有压缩过的

**Comment by monkeyWie** [comment]
@darker50 
感谢你提出的bug，现在问题已经修复了，手机上的证书不会提示不安全了。
可以开启浏览器上访问CA证书，代码如下
···
pipeline.addLast(new CertDownIntercept());  //开启网页下载证书功能
···
然后访问http://serverIp:serverPort就可以看到下载页面了
![image](https://user-images.githubusercontent.com/13160176/33648000-cb1edc92-da92-11e7-9c8d-43b36861de1a.png)

**Comment by monkeyWie** [comment]
@darker50 
关于gzip的处理可以用java自带的GZIPInputStream来处理
```
pipeline.addLast(new HttpProxyIntercept() {

	private boolean isGzip = false;
	private ByteArrayOutputStream outputStream;

	@Override
	public void afterResponse(Channel clientChannel, Channel proxyChannel,
	  HttpResponse httpResponse,
	  HttpProxyInterceptPipeline pipeline) throws Exception {
	this.httpResponse = httpResponse;
	if ("gzip".equalsIgnoreCase(
	    httpResponse.headers().get(HttpHeaderNames.CONTENT_ENCODING))) {
	  isGzip = true;
	  outputStream = new ByteArrayOutputStream();
	}
	//转到下一个拦截器处理
	pipeline.afterResponse(clientChannel, proxyChannel, httpResponse);
	}

	@Override
	public void afterResponse(Channel clientChannel, Channel proxyChannel,
	  HttpContent httpContent,
	  HttpProxyInterceptPipeline pipeline) throws Exception {
	if (isGzip) {
	  ByteBuf temp = httpContent.content().slice();
	  //缓存在ByteArrayOutputStream里
	  temp.readBytes(outputStream, temp.readableBytes());
	  if (httpContent instanceof LastHttpContent) {
	    //gzip解码
	    try (BufferedReader br = new BufferedReader(new InputStreamReader(
	        new GZIPInputStream(
	            new ByteArrayInputStream(outputStream.toByteArray()))))) {
	      String line;
	      while ((line = br.readLine()) != null) {
	        System.out.println(line);
	      }
	    } catch (Exception e) {
	      e.printStackTrace();
	    }
	  }
	}
	pipeline.afterResponse(clientChannel, proxyChannel, httpContent);
	}
});
```

**Comment by darker50** [comment]
@monkeyWie 
好的，非常感谢。有问题再麻烦你解答。

**Comment by weirenren** [comment]
> 确认了，报那些错误的原因就是证书的问题，当时用手机请求的时候后台还有一些请求，那些请求导致报那个证书的问题，感谢，感谢。
> 拦截器对gzip压缩结束直接打印的结果会有乱码，我目前的处理方法，是请求的时候不用压缩，返回的结果也就没有压缩过的

仁兄，请教下”当时用手机请求的时候后台还有一些请求，那些请求导致报那个证书的问题“ 这句话是什么意思啊，能详细展开吗
